-- AlterTable: add new energy/power fields to Telemetry1m
ALTER TABLE "Telemetry1m"
  ADD COLUMN IF NOT EXISTS "freqInAvg"   DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "freqOutAvg"  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pInWAvg"     DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pInWMax"     DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pOutWAvg"    DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pOutWMax"    DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pfInAvg"     DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pfOutAvg"    DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "qInVarAvg"   DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "qOutVarAvg"  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "eInKwhLast"  DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "eOutKwhLast" DOUBLE PRECISION;
