#Requires -RunAsAdministrator
<#
.SYNOPSIS
  UMS post-install setup — called by Inno Setup after files are copied.
  Creates .env, runs DB migrations, registers Windows service, opens firewall.
#>
param(
  [string]$InstallDir  = "C:\Program Files\UMS",
  [string]$DbHost      = "localhost",
  [string]$DbPort      = "5432",
  [string]$DbName      = "ums_local",
  [string]$DbUser      = "ums_user",
  [string]$DbPass      = "",
  [string]$AdminPass   = "",
  [string]$LicensePublicKeyPem = "",
  [string]$LicensePublicKeyPath = "",
  [string]$MqttPort    = "1883",
  [string]$HttpPort    = "3303"
)

$ErrorActionPreference = "Stop"
$LogFile = "$InstallDir\logs\install.log"
New-Item -ItemType Directory -Force -Path "$InstallDir\logs" | Out-Null

function Log($msg) {
  $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
  "$ts  $msg" | Tee-Object -FilePath $LogFile -Append | Write-Host
}

# ── 1. Locate Node ─────────────────────────────────────────────────────────
Log "Checking Node.js..."
$NodeExe = (Get-Command node -ErrorAction SilentlyContinue)?.Source
if (-not $NodeExe) {
  Log "Node.js not found — running silent installer..."
  $NodeMsi = "$InstallDir\tools\node-v24.15.0-x64.msi"
  if (Test-Path $NodeMsi) {
    Start-Process msiexec.exe -ArgumentList "/i `"$NodeMsi`" /quiet /norestart ADDLOCAL=ALL" -Wait
    # Refresh PATH
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    $NodeExe = (Get-Command node -ErrorAction SilentlyContinue)?.Source
  }
}
if (-not $NodeExe) {
  Log "ERROR: Node.js install failed. Install manually from https://nodejs.org"
  exit 1
}
Log "Node.js: $NodeExe"

# ── 2. Generate random auth token ──────────────────────────────────────────
Log "Generating auth token..."
$AuthToken = [System.Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))

if (-not $LicensePublicKeyPem -and $LicensePublicKeyPath) {
  if (-not (Test-Path $LicensePublicKeyPath)) {
    Log "ERROR: license public key file not found: $LicensePublicKeyPath"
    exit 1
  }
  $LicensePublicKeyPem = Get-Content -Raw -LiteralPath $LicensePublicKeyPath
}
if (-not $LicensePublicKeyPem) {
  Log "ERROR: UMS license public key is required. Installer cannot start the production service without UMS_LICENSE_PUBLIC_KEY_PEM."
  exit 1
}
$LicensePublicKeyEnv = ($LicensePublicKeyPem.Trim() -replace "`r?`n", "\n")

# ── 3. Hash admin password with bcrypt (using bundled Node) ───────────────
Log "Hashing admin password..."
$HashScript = @"
const bcrypt = require('bcryptjs');
const hash = bcrypt.hashSync(process.argv[1], 12);
process.stdout.write(hash);
"@
$HashScript | Out-File -FilePath "$env:TEMP\hash.js" -Encoding utf8
$BcryptDir = "$InstallDir\app\node_modules\bcryptjs"
$AdminHash = & $NodeExe -e "const b=require('$($BcryptDir.Replace('\','\\'))');process.stdout.write(b.hashSync('$AdminPass',12));" 2>&1
if ($LASTEXITCODE -ne 0) {
  Log "ERROR: bcrypt hash generation failed. Installation stopped; plaintext passwords are not written."
  exit 1
}
Remove-Item "$env:TEMP\hash.js" -ErrorAction SilentlyContinue

# ── 4. Write .env ──────────────────────────────────────────────────────────
Log "Writing .env..."
$DatabaseUrl = "postgresql://${DbUser}:${DbPass}@${DbHost}:${DbPort}/${DbName}"
$EnvContent = @"
# Generated by UMS installer — $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
DATABASE_URL=$DatabaseUrl
UPS_AUTH_TOKEN=$AuthToken
UPS_AUTH_PASSWORD_HASH=$AdminHash
UMS_LICENSE_PUBLIC_KEY_PEM=$LicensePublicKeyEnv
MQTT_PORT=$MqttPort
PORT=$HttpPort
NODE_ENV=production
"@
$EnvContent | Out-File -FilePath "$InstallDir\app\.env" -Encoding utf8
Log ".env written."

# ── 5. Run Prisma migrations ───────────────────────────────────────────────
Log "Running database migrations..."
$AppDir = "$InstallDir\app"
Set-Location $AppDir
$env:DATABASE_URL = $DatabaseUrl
& $NodeExe "$AppDir\node_modules\.bin\prisma" migrate deploy 2>&1 | Tee-Object -FilePath $LogFile -Append
if ($LASTEXITCODE -ne 0) {
  Log "migrate deploy failed — trying db push..."
  & $NodeExe "$AppDir\node_modules\.bin\prisma" db push --accept-data-loss 2>&1 | Tee-Object -FilePath $LogFile -Append
  if ($LASTEXITCODE -ne 0) { Log "ERROR: DB setup failed. Check $LogFile"; exit 1 }
}
Log "Database ready."

# ── 6. Seed database (admin user) ─────────────────────────────────────────
Log "Seeding database..."
& $NodeExe "$AppDir\node_modules\tsx\dist\cli.mjs" "$AppDir\scripts\seed.ts" -- --demo 2>&1 | Tee-Object -FilePath $LogFile -Append
# Seed failures are non-fatal (DB may already have data)
Log "Seed done (errors above are non-fatal if re-installing)."

# ── 7. Register Windows service with NSSM ─────────────────────────────────
Log "Registering UMS Windows service..."
$NssmExe  = "$InstallDir\tools\nssm.exe"
$ServiceName = "UMSDashboard"

# Remove existing service if present
& $NssmExe stop  $ServiceName 2>&1 | Out-Null
& $NssmExe remove $ServiceName confirm 2>&1 | Out-Null

& $NssmExe install $ServiceName $NodeExe "$AppDir\.next\standalone\server.js"
& $NssmExe set $ServiceName AppDirectory $AppDir
& $NssmExe set $ServiceName AppEnvironmentExtra `
    "DATABASE_URL=$DatabaseUrl" `
    "UPS_AUTH_TOKEN=$AuthToken" `
    "UPS_AUTH_PASSWORD_HASH=$AdminHash" `
    "UMS_LICENSE_PUBLIC_KEY_PEM=$LicensePublicKeyEnv" `
    "PORT=$HttpPort" `
    "MQTT_PORT=$MqttPort" `
    "NODE_ENV=production"
& $NssmExe set $ServiceName DisplayName "UPS Management System"
& $NssmExe set $ServiceName Description "UMS dashboard, MQTT broker, and telemetry worker"
& $NssmExe set $ServiceName Start SERVICE_AUTO_START
& $NssmExe set $ServiceName AppStdout "$InstallDir\logs\ums-stdout.log"
& $NssmExe set $ServiceName AppStderr "$InstallDir\logs\ums-stderr.log"
& $NssmExe set $ServiceName AppRotateFiles 1
& $NssmExe set $ServiceName AppRotateBytes 10485760

Log "Service registered."

# ── 8. Open firewall ───────────────────────────────────────────────────────
Log "Opening firewall ports..."
netsh advfirewall firewall delete rule name="UMS MQTT" | Out-Null
netsh advfirewall firewall delete rule name="UMS Dashboard" | Out-Null
netsh advfirewall firewall add rule name="UMS MQTT" protocol=TCP dir=in localport=$MqttPort action=allow
netsh advfirewall firewall add rule name="UMS Dashboard" protocol=TCP dir=in localport=$HttpPort action=allow
Log "Firewall rules added for ports $MqttPort (MQTT) and $HttpPort (HTTP)."

# ── 9. Start service ───────────────────────────────────────────────────────
Log "Starting UMS service..."
& $NssmExe start $ServiceName
Start-Sleep -Seconds 3
$Status = (Get-Service $ServiceName -ErrorAction SilentlyContinue)?.Status
Log "Service status: $Status"

# ── 10. Write open-dashboard helper ────────────────────────────────────────
@"
@echo off
start http://localhost:$HttpPort
"@ | Out-File -FilePath "$InstallDir\scripts\open-dashboard.bat" -Encoding ascii

Log "Installation complete. Dashboard: http://localhost:$HttpPort"
exit 0
